"""Response and request models shared across the /api routers.

UserOut exists so that no route can leak password_hash by accident: it lists the
fields that may leave the process, and anything not on the list cannot.
"""
from __future__ import annotations

import sqlite3

from pydantic import BaseModel, Field


class UserOut(BaseModel):
    id: int
    username: str
    display_name: str
    role: str
    must_change_password: bool
    disabled: bool = False

    @classmethod
    def from_row(cls, row: sqlite3.Row) -> "UserOut":
        return cls(
            id=row["id"],
            username=row["username"],
            display_name=row["display_name"],
            role=row["role"],
            must_change_password=bool(row["must_change_password"]),
            disabled=bool(row["disabled"]),
        )


class LoginRequest(BaseModel):
    username: str = Field(min_length=1, max_length=64)
    password: str = Field(min_length=1, max_length=256)


class LoginResponse(BaseModel):
    token: str
    user: UserOut


class ChangePasswordRequest(BaseModel):
    current_password: str = Field(min_length=1, max_length=256)
    # Eight is not a security posture, it is a floor. These passwords are
    # generated by the server; the minimum only guards a hand-typed replacement.
    new_password: str = Field(min_length=8, max_length=256)


class OkResponse(BaseModel):
    ok: bool = True


class MeResponse(BaseModel):
    user: UserOut
    settings: dict
    server_time: str
